name: "Lint Markdown"
description: "Lints markdown using the markdownlint-cli."
inputs:
  options:
    description: "Options to provide to markdownlint-cli"
    required: false

  directory:
    description: "The directory containing markdown to lint"
    required: false
    default: docs

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install markdownlint-cli
      shell: bash
      run: npm install -g markdownlint-cli

    - name: Lint markdown
      shell: bash
      run: markdownlint ${{ inputs.options }} ${{ inputs.directory }}
